name: deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-home:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy main site to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_NAME }}
          password: ${{ secrets.REMOTE_PASS }}
          source: 'index.html'
          target: ${{ secrets.REMOTE_TARGET }}
