name: deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to server
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_NAME }}
          pass: ${{ secrets.REMOTE_PASS }}
          connect_timeout: 10s
          local: 'index.html'
          remote: ${{ secrets.REMOTE_TARGET }}
